version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning --port 6379
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local